service: kfs3

custom:
  stage: ${opt:stage, 'dev'}
  serviceName: kfs3
  S3BucketNameForFirehoseDestination: ${env:FIREHOSE_DESTINATION_BUCKET}
  Stream: ${self:service}-${self:custom.stage}-app-stream


provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'


functions:
  transform:
    handler: handler.transform
    name: ${self:service}-${self:custom.stage}-kfs3-transform-lambda
    timeout: 60
  


resources:
#  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/stream.yml)}
  - ${file(resources/firehose.yml)}

 
